spring.application.name=findit-backend

spring.datasource.url=jdbc:mariadb://58ea917d-11a0-4864-979f-34a7070d9edc.ma.bw-cloud-instance.org:3307/findit-test
spring.datasource.username=findit1
spring.datasource.password=hUZ2lKRbymAVuox3
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.port=8080