spring.application.name=findit-backend

server.port=${PORT:8080}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
app.demo-data.enabled=${APP_DEMO_DATA_ENABLED:true}
app.security.enabled=${APP_SECURITY_ENABLED:false}
app.auth.audience=${AUTH0_AUDIENCE:}
app.auth.claim-namespace=${APP_AUTH_CLAIM_NAMESPACE:https://findit.htwg-konstanz.de/}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI:}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.mariadb.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.h2.console.enabled=false